CREATE TABLE Users(
    Id UUID NOT NULL PRIMARY KEY,
    Name VARCHAR(125) NOT NULL,
    Mail VARCHAR(200) NOT NULL UNIQUE,
    Login VARCHAR(50) NOT NULL UNIQUE,
    Password VARCHAR(50) NOT NULL,
    LastUpdate DATE NOT NULL DEFAULT CURRENT_DATE,
    Usertype VARCHAR(30) NOT NULL,
    AddressId UUID NOT NULL UNIQUE

    FOREIGN KEY (AddressId) REFERENCES Users(Id)
);