CREATE TABLE Users(
    id CHAR(36) NOT NULL PRIMARY KEY,
    name VARCHAR(125) NOT NULL,
    mail VARCHAR(200) NOT NULL UNIQUE,
    login VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(50) NOT NULL,
    last_update TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_type VARCHAR(30) NOT NULL,
    address_id CHAR(36) NOT NULL UNIQUE,

    FOREIGN KEY (address_id) REFERENCES Users(id)
);